In [ ]:
import numpy as np

def basicArithmaticOperations():
  while True:
    arrStr = input("Enter numbers with space for array 1: ")
    arrStr1 = input("Enter nubers with space for array 2: ")
    list1 = arrStr.split()
    list2 = arrStr1.split()
    try:
      arr1 = np.array(list1, dtype=int)
      arr2 = np.array(list2, dtype=int)
      print("Array: ", arr1)
      print("Array: ", arr2)
      print("Addition: ", np.add(arr1, arr2))
      print("Subtraction: ", np.subtract(arr1, arr2))
      print("Multiplication: ", np.multiply(arr1, arr2))
      print("Division: ", np.divide(arr1, arr2))
      print("Power: ", np.pow(arr1,arr2))
      break
    except Exception as e:
      print("Error: ", e)

def staticalOperations():
  while True:
    arrStr = input("Enter numbers with space for array: ")
    list1 = arrStr.split()
    try:
      arr1 = np.array(list1, dtype=int)
      print("Array: ", arr1)
      print("Mean: ", np.mean(arr1))
      print("Median: ", np.median(arr1))
      print("Standard Deviation: ", np.std(arr1))
      print("Variance: ", np.var(arr1))
      print("Minimum: ", np.min(arr1))
      print("Maximum: ", np.max(arr1))
      print("Sum: ", np.sum(arr1))
      print("Product: ", np.prod(arr1))
      print("Datatype: ",arr1.dtype)
      print("size: ", arr1.size)
      print("Shape: ", arr1.shape)
      break
    except Exception as e:
      print("Error: ", e)

def arrayManipulation():
  while True:
    arrStr = input("Enter numbers with space for array: ")
    list1 = arrStr.split()
    try:
      arr1 = np.array(list1, dtype=int)
      print("Array: ", arr1)
      possibleReshapes(arr1)
      print("\nSorted Array:", np.sort(arr1))
      print("Reverse Sorted Array:", np.sort(arr1)[::-1])
      print("Unique Values:", np.unique(arr1))
      print("First Element:", arr1[0])
      print("Last Element:", arr1[-1])
      mean = np.mean(arr1)
      print("Filtered Value Greater than mean: ",np.where(arr1>mean))
      break
    except Exception as e:
      print("Error: ", e)

def possibleReshapes(arr):
    print("\n Possible reshapes (rows, cols):")
    total = arr.size
    print("\n=== Possible 2D Reshapes (rows, cols) ===")
    for i in range(1, total + 1):
        if total % i == 0:
            print(f"Shapes of an 2D array {i, total//i}")
            print(arr.reshape(i,total//i))

    print("\n=== Possible 3D Reshapes (rows, cols, elements) ===")
    for r in range(1, total+1):
       if total % r == 0:
            remaining = total // r
            for c in range(1, remaining + 1):
                if remaining % c == 0:
                    e = remaining // c
                    print(f"Rows: {r}, Cols: {c}, Elements: {e}")
                    shape = (r, c, e)
                    print(f"Shape: {shape}")
                    print(arr.reshape(shape), "\n")



def matchchoices():
  while True:
    print("\n=======================================")
    print("1. Basics Arithmetic Operations")
    print("2. Statical Operations")
    print("3. Array Manipulations")
    print("4. Exit")
    print("=======================================")
    try:
     choice = int(input("Enter your choice: "))
     if choice == 1:
       basicArithmaticOperations()
     elif choice == 2:
       staticalOperations()
     elif choice == 3:
       arrayManipulation()
     elif choice == 4:
       print("Exiting program...")
       break
    except Exception as e:
      print("Error: ", e)

matchchoices()


1. Basics Arithmetic Operations
2. Statical Operations
3. Array Manipulations
4. Exit
Enter your choice: 3
Enter numbers with space for array: 1 2 3 4
Array:  [1 2 3 4]

 Possible reshapes (rows, cols):

=== Possible 2D Reshapes (rows, cols) ===
Shapes of an 2D array (1, 4)
[[1 2 3 4]]
Shapes of an 2D array (2, 2)
[[1 2]
 [3 4]]
Shapes of an 2D array (4, 1)
[[1]
 [2]
 [3]
 [4]]

=== Possible 3D Reshapes (rows, cols, elements) ===
Rows: 1, Cols: 1, Elements: 4
Shape: (1, 1, 4)
[[[1 2 3 4]]] 

Rows: 1, Cols: 2, Elements: 2
Shape: (1, 2, 2)
[[[1 2]
  [3 4]]] 

Rows: 1, Cols: 4, Elements: 1
Shape: (1, 4, 1)
[[[1]
  [2]
  [3]
  [4]]] 

Rows: 2, Cols: 1, Elements: 2
Shape: (2, 1, 2)
[[[1 2]]

 [[3 4]]] 

Rows: 2, Cols: 2, Elements: 1
Shape: (2, 2, 1)
[[[1]
  [2]]

 [[3]
  [4]]] 

Rows: 4, Cols: 1, Elements: 1
Shape: (4, 1, 1)
[[[1]]

 [[2]]

 [[3]]

 [[4]]] 


Sorted Array: [1 2 3 4]
Reverse Sorted Array: [4 3 2 1]
Unique Values: [1 2 3 4]
First Element: 1
Last Element: 4
Filtered Value Gre